//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToplantıRezervasyon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Oda
    {
        public int ID { get; set; }
        public string Salonİsmi { get; set; }
        public Nullable<int> OturmaSayısı { get; set; }
        public Nullable<int> BilgisayarSayısı { get; set; }
        public string Esya { get; set; }
    }
}
